#ifndef LIBRARYTESTS_GLOBAL_H
#define LIBRARYTESTS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBRARYTESTS_LIBRARY)
#  define LIBRARYTESTSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBRARYTESTSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBRARYTESTS_GLOBAL_H
